// export let url = window.location.origin
// export let url = 'http://127.0.0.1:5000'
// export let url = 'http://192.168.88.221:5000'
export let url = 'http://192.168.88.197:5000'
export let GET_RTMP_URL = `${url}/get_rtmp_url`
export let ADD_RTMP_URL = `${url}/add_rtmp_url`
export let DEL_RTMP_URL = `${url}/del_rtmp_url`
export let GET_ALL_PERSONS = `${url}/all_persons`
export let UPLOAD_IMG_TMP = `${url}/upload_tmp`
export let ADD_PERSON = `${url}/add_person`
export let GET_REMOTE_CONFIG = `${url}/get_remote_config`
export let CHANGE_REMOTE_CONFIG = `${url}/change_remote_config`
export let CAMERAIMGS = `${url}/cameraImgs`
export let CAMERAPERSONS = `${url}/cameraPersons`